### ISSUE TITLE
Requesting your help in merge queue

### ISSUE THREAD

**Issue by Patel-Muhammad** [DorianBD/AI#1]
Hi @DorianBD I am GSoC23 contributor in oppia and this is my last week for the project and I have deadline to meet by 7nov so I need to get my 3 PRs merged by that. 

Currently your PR is there in the merge queue and it is taking too long to wait for my PRs to get merged. 

Can please cooperate and help by removing your PR from the merge queue and please feel to add it again once my PRs are merged. Thanks!

**Comment by DorianBD** [comment]
Hi @Patel-Muhammad , I'd like to help, but dont know how to do what you asked. It's my first pull request. I see that oppiabot is asking me to assign someone to merge, and I haven't assigned anyone at the moment, so I think it's not slowing down the processing of your pull requests. I'm not sure, so if I'm wrong, let me know what to do so that you can merge your pull requests.
